[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[phases.start]
cmd = "gunicorn debug_buddy.wsgi --log-file - --bind 0.0.0.0:${PORT:-8000}"
