# Generated by Django 5.2.4 on 2025-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_input', models.TextField(verbose_name='Log')),
                ('ai_response', models.TextField(verbose_name='Resposta da IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
