# Generated by Django 5.2.4 on 2025-07-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_loganalysis_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loganalysis',
            options={'verbose_name_plural': 'Log Analyses'},
        ),
        migrations.AddField(
            model_name='loganalysis',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='loganalysis',
            name='ai_response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loganalysis',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='loganalysis',
            name='log_input',
            field=models.TextField(),
        ),
    ]
